version: '3'

services:
  db:
    container_name: gallery_db
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    

  backend:
    container_name: gallery_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    build: .